### ISSUE TITLE
publish the demo

### ISSUE THREAD

**Issue by dmengelt** [google-pay/pay-server-demos#4]
It would be nice if the demo can be checked out not only locally. Therefore I suggest to find a way to deploy it somewhere publicly.

**Update:** Ok this would mean that for each PSP test credentials are needed.

**Comment by gubasza** [comment]
@dmengelt

**Comment by gcatanese** [comment]
Hey @dmengelt I had a shot at it and successfully deployed on Gitpod, see https://github.com/gcatanese/pay-server-demos/tree/gitpod-workspace

The only open point would be how to deal with the `config.json` which is needed to run the application: in my solution the file is provided without the actual keys and, instead, the environment variables are used. 
Is it acceptable to commit the file (with no keys, only as a placeholder)? At the moment the file is git ignored but this prevents Gitpod to run (failure as the file is not found).

The same problem would be when deploying on other (cloud) platforms (unless the `config.json` is created/injected at some point during the deployment).

**Comment by dmengelt** [comment]
Hi @gcatanese 
Yeah. This is exactly the problem. I also don't have a solution for this.

**Comment by gcatanese** [comment]
The way I solved that is to provide a `config-test.json` which is read only when the `config.json` is not found (ie when deploying on cloud). Feel free to take a look https://github.com/gcatanese/pay-server-demos

The example uses `adyen` and Gitpod, but it works the same for other PSPs deploying on different platforms.

**Comment by dmengelt** [comment]
@gcatanese I'm closing this issue. Your solution looks good to me.
